language: node_js
node_js:
- 12.16.3
before_install:
- npm update
branches:
  only:
  - master
  - develop
notifications:
  slack:
    secure: PpIOxaVH4LJsqN4/kdlITVHxVHBZyQeJl1NJxK70i/wnBP/p0t0iDGNpQOnspvmfgRfNfwvrDFeren8NzAEJssYTtNJhv8iNl+7wX7D8oarCSiWyaOenDtOLf498ObxKDD7KtV6WkqPCunwnJwX6VVcbHsHXGJ5GnlXaRs4yflP4x4xy6js3D9A4ygmrHzGe0QXwLKdTboAhEwT0pzNy726PKV5Z4iGIzV7yu22tkarErlSWWZSvmYlr2CibGGCddrQvXznACqmH/Qryd89ocOr8w2kt17KvbFLiJjftxCpSggKBWjeG+O6rTaOCH3sNsjIPssmNMCN1fztxxD2f8zhpZc/aFE2gNGlRqHXnaeLdTdSGL7JPyPgQQDdbUMV59PnRCBmMbh1REyzkx+hL7ikaqRiEnJHpQs0d1aZYPZIF3OTe2EzCEHVrS9qEeVI9Sbc9JvFCgfPOQurkRaTStFfDA2AFwSPX4uTZlSUA+ums3lB3qvOxHi9PE+OFflgikFB/kroC8pbwpIESpmr/hn2EWTCKsYXepNdCnUIbobPFW74rV3B8zKo3CHxuQxr7RgNoZPAZb3R2lE/PuM1f7t29aZTyK0/UMMhOMHOgxn9Cuy6q46SN03obCJxV7dtFbACJKHIkyLhKS/9qGMgBd6291N37njA6RftTiEYwJjA=
