version: "3"
services:
  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - "80:80"
      - "433:433"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ../volumes/.static_root/:/static/
      - ../volumes/certbot/conf:/etc/letsencrypt
      - ../volumes/certbot/www:/var/www/certbot
    restart: "unless-stopped"
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ../volumes/certbot/conf:/etc/letsencrypt
      - ../volumes/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  express1:
    build:
      context: ./server
    container_name: express1
    expose:
      - "3000"
    volumes:
      - ./src/express1:/src
      - /src/node_modules
    restart: "unless-stopped"
  express2:
    build:
      context: ./server
    container_name: express2
    expose:
      - "3000"
    volumes:
      - ./src/express2:/src
      - /src/node_modules
    restart: "unless-stopped"
