export default {
  HEALTH_CHECK: 'health check',
  NULL_VALUE: '필요한 값이 없습니다.',
  OUT_OF_VALUE: '파라미터 값이 잘못 되었습니다.',
  BODY_VALUE_ERROR: 'Body 타입이 잘못 되었습니다.',
  INTERNAL_SERVER_ERROR: '서버 내부 오류',
  DUPLICATE_VALUE_ERROR: '중복된 파라미터 값',
  SIGN_UP_SUCCESS: '회원가입 성공',
  SIGN_IN_SUCCESS: '로그인 성공',
  SIGN_UP_FAIL: '회원가입 실패',
  SIGN_IN_FAIL: '로그인 실패',
  POSSIBLE_ID: '사용 가능한 ID입니다.',
  DUPLICATE_ID: '사용 불가능한 ID입니다.',
  MISS_MATCH_USER_INFO: 'ID 또는 비밀번호가 일치하지 않습니다',
  MISS_MATCH_PASSWORD: '비밀번호가 일치하지 않습니다',
  MATCH_PASSWORD: '비밀번호가 일치합니다',
  TEMP_PASSWORD_ISSUE_EXCEDDED: '임시 비밀번호 발급 횟수 초과',
  UNAUTHORIZED: '권한이 없습니다',
  SAME_PASSWORD_AND_NEW_PASSWORD: '현재 비밀번호와 새로운 비밀번호가 동일합니다.',

  DB_ERROR: '데이터베이스 에러',
  EMPTY_TOKEN: '헤더에 토큰이 없음',
  EXPIRED_TOKEN: '유효기간이 지난 토큰',
  INVALID_TOKEN: '잘못된 토큰',

  X_CREATE_SUCCESS: (x: string) => `${x} 생성 성공`,
  X_CREATE_FAIL: (x: string) => `${x} 생성 실패`,
  X_READ_ALL_SUCCESS: (x: string) => `${x} 전체 조회 성공`,
  X_READ_ALL_FAIL: (x: string) => `${x} 전체 조회 실패`,
  X_READ_SUCCESS: (x: string) => `${x} 조회 성공`,
  X_READ_FAIL: (x: string) => `${x} 조회 실패`,
  X_UPDATE_SUCCESS: (x: string) => `${x} 수정 성공`,
  X_UPDATE_FAIL: (x: string) => `${x} 수정 실패`,
  X_DELETE_SUCCESS: (x: string) => `${x} 삭제 성공`,
  X_DELETE_FAIL: (x: string) => `${x} 삭제 실패`,
  X_SUCCESS: (x: string) => `${x} 성공`,
  X_FAIL: (x: string) => `${x} 실패`,
  NO_X: (x: string) => `존재하지 않는 ${x}`,
  ALREADY_X: (x: string) => `이미 존재하는 ${x}`,
};
