name: Node.js-CI
on:
  pull_request:
    branches:    
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2.1.4
      with:
        node-version: '12'
    - run: npm ci
    - run: npm run test:coverage
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        DATABASE_DIALECT: ${{ secrets.DATABASE_DIALECT }}
        DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
        DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
        NODEMAILER_PASS: ${{ secrets.NODEMAILER_PASS }}
        NODEMAILER_USER: ${{ secrets.NODEMAILER_USER }}
        TOKEN_SECRET_KEY: ${{ secrets.TOKEN_SECRET_KEY }}
        
    - name: Report Coverage
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
      if: success()
    
    - name: Close Pull
      uses: peter-evans/close-pull@v1
      with:
        comment: Failed to pass the test
      if: failure()
